import pandas as pd

movies = [
    # Action / Sci-Fi / Superhero
    {"id": 1, "title": "The Avengers", "genre": "Action, Sci-Fi", "description": "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.", "image_url": "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg"},
    {"id": 2, "title": "Avengers: Age of Ultron", "genre": "Action, Sci-Fi", "description": "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.", "image_url": "https://image.tmdb.org/t/p/w500/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg"},
    {"id": 3, "title": "Avengers: Infinity War", "genre": "Action, Sci-Fi", "description": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.", "image_url": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg"},
    {"id": 4, "title": "Avengers: Endgame", "genre": "Action, Sci-Fi", "description": "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.", "image_url": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg"},
    {"id": 5, "title": "The Batman", "genre": "Action, Crime, Drama", "description": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.", "image_url": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg"},
    {"id": 6, "title": "The Dark Knight", "genre": "Action, Crime, Drama", "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", "image_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg"},
    {"id": 7, "title": "Batman Begins", "genre": "Action, Crime, Drama", "description": "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.", "image_url": "https://image.tmdb.org/t/p/w500/1P3ZyEq02wcTMd3iE4ebtLvncvH.jpg"},
    {"id": 8, "title": "The Dark Knight Rises", "genre": "Action, Crime, Drama", "description": "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.", "image_url": "https://image.tmdb.org/t/p/w500/85cWkCVftiVs0BV86Gx05F85VPF.jpg"},
    {"id": 9, "title": "Spider-Man: No Way Home", "genre": "Action, Sci-Fi", "description": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.", "image_url": "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg"},
    {"id": 10, "title": "Iron Man", "genre": "Action, Sci-Fi", "description": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.", "image_url": "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg"},
    
    # Sci-Fi / Space
    {"id": 11, "title": "Interstellar", "genre": "Sci-Fi, Drama", "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "image_url": "https://image.tmdb.org/t/p/w500/gEU2QniL6E8AHtMY4kO30FzNS01.jpg"},
    {"id": 12, "title": "Inception", "genre": "Sci-Fi, Action", "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", "image_url": "https://image.tmdb.org/t/p/w500/9gk7admal4zlE2tQXMf1y9wMnF9.jpg"},
    {"id": 13, "title": "The Matrix", "genre": "Sci-Fi, Action", "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", "image_url": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpQUk5H.jpg"},
    {"id": 14, "title": "Blade Runner 2049", "genre": "Sci-Fi, Drama", "description": "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.", "image_url": "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg"},
    {"id": 15, "title": "Dune", "genre": "Sci-Fi, Adventure", "description": "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.", "image_url": "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg"},
    {"id": 16, "title": "Arrival", "genre": "Sci-Fi, Drama", "description": "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", "image_url": "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63C3cwpfF9rFMDV.jpg"},
    {"id": 17, "title": "The Martian", "genre": "Sci-Fi, Adventure", "description": "An astronaut becomes stranded on Mars after his team assumes him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.", "image_url": "https://image.tmdb.org/t/p/w500/5BHuvQ6p9kfc091DJ8OIQhHSBUs.jpg"},
    
    # Drama / Crime
    {"id": 18, "title": "The Godfather", "genre": "Crime, Drama", "description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", "image_url": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"},
    {"id": 19, "title": "Pulp Fiction", "genre": "Crime, Drama", "description": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", "image_url": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg"},
    {"id": 20, "title": "Fight Club", "genre": "Drama", "description": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.", "image_url": "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg"},
    {"id": 21, "title": "The Shawshank Redemption", "genre": "Drama", "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", "image_url": "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg"},
    {"id": 22, "title": "Goodfellas", "genre": "Crime, Drama", "description": "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.", "image_url": "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg"},
    {"id": 23, "title": "Joker", "genre": "Crime, Drama, Thriller", "description": "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.", "image_url": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"},
    
    # Animation
    {"id": 24, "title": "Spider-Man: Into the Spider-Verse", "genre": "Animation, Action, Adventure", "description": "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.", "image_url": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg"},
    {"id": 25, "title": "The Lion King", "genre": "Animation, Drama", "description": "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", "image_url": "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg"},
    {"id": 26, "title": "Spirited Away", "genre": "Animation, Fantasy", "description": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.", "image_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUKGnSxQbUgZ.jpg"},
    {"id": 27, "title": "Toy Story", "genre": "Animation, Comedy", "description": "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.", "image_url": "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg"},
    {"id": 28, "title": "Up", "genre": "Animation, Adventure", "description": "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.", "image_url": "https://image.tmdb.org/t/p/w500/vpbaStTMt8qqXaEgnOR2EE4DNJk.jpg"},
    {"id": 29, "title": "Coco", "genre": "Animation, Fantasy", "description": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.", "image_url": "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg"},
    
    # Horror / Thriller
    {"id": 30, "title": "The Shining", "genre": "Horror, Drama", "description": "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.", "image_url": "https://image.tmdb.org/t/p/w500/b4gYVcl8pParX8AjkN90iQrWrWO.jpg"},
    {"id": 31, "title": "Get Out", "genre": "Horror, Mystery", "description": "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he could have never imagined.", "image_url": "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg"},
    {"id": 32, "title": "Psycho", "genre": "Horror, Thriller", "description": "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.", "image_url": "https://image.tmdb.org/t/p/w500/81d8oyEFgj7Z5QKiBwNEScFExB6.jpg"},
    {"id": 33, "title": "Se7en", "genre": "Crime, Thriller", "description": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.", "image_url": "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg"},
    
    # Romance
    {"id": 34, "title": "Titanic", "genre": "Romance, Drama", "description": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "image_url": "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg"},
    {"id": 35, "title": "The Notebook", "genre": "Romance, Drama", "description": "An epic love story centered around an older man who reads aloud a notebook to an older, invalid woman.", "image_url": "https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg"},
    {"id": 36, "title": "La La Land", "genre": "Romance, Musical", "description": "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair.", "image_url": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWzI16xOkCjKerpxnP.jpg"},
    
    # Fantasy
    {"id": 37, "title": "Harry Potter and the Sorcerer's Stone", "genre": "Fantasy, Adventure", "description": "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.", "image_url": "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg"},
    {"id": 38, "title": "The Lord of the Rings: The Fellowship of the Ring", "genre": "Fantasy, Adventure", "description": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", "image_url": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg"},
    {"id": 39, "title": "The Lord of the Rings: The Return of the King", "genre": "Fantasy, Adventure", "description": "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.", "image_url": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg"},
    
    # Comedy
    {"id": 40, "title": "Superbad", "genre": "Comedy", "description": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.", "image_url": "https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg"},
    {"id": 41, "title": "The Hangover", "genre": "Comedy", "description": "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.", "image_url": "https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg"},
    {"id": 42, "title": "Deadpool", "genre": "Action, Comedy", "description": "Deadpool tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.", "image_url": "https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I4770sC1a2h7.jpg"},
    
    # More Classics
    {"id": 43, "title": "Back to the Future", "genre": "Adventure, Comedy, Sci-Fi", "description": "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.", "image_url": "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iFngXB.jpg"},
    {"id": 44, "title": "Gladiator", "genre": "Action, Drama", "description": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", "image_url": "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg"},
    {"id": 45, "title": "Jurassic Park", "genre": "Adventure, Sci-Fi", "description": "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.", "image_url": "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoOEFaDzIBc.jpg"},
    {"id": 46, "title": "Schindler's List", "genre": "Biography, Drama, History", "description": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.", "image_url": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pTXMYjj6w.jpg"},
    {"id": 47, "title": "The Silence of the Lambs", "genre": "Crime, Drama, Thriller", "description": "Clarice Starling is a top student at the FBI's training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.", "image_url": "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg"},
    {"id": 48, "title": "Saving Private Ryan", "genre": "Drama, War", "description": "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.", "image_url": "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlVal9.jpg"},
    {"id": 49, "title": "The Green Mile", "genre": "Crime, Drama, Fantasy", "description": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments.", "image_url": "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg"},
    {"id": 50, "title": "Parasite", "genre": "Comedy, Drama, Thriller", "description": "All-unemployed Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", "image_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"}
]

df = pd.DataFrame(movies)
df.to_csv("data/movies.csv", index=False)
print("Generated data/movies.csv with 50 movies.")
